// PowerController.swift -- PSCI (Power State Coordination Interface) handler.
// VortexDevices
//
// Implements the ARM PSCI v1.1 specification (ARM DEN0022D) for virtual
// machine power management. This is NOT an MMIO device -- it handles
// HVC and SMC calls intercepted by the vCPU exit handler.
//
// Supported PSCI functions:
//   0x8400_0000  PSCI_VERSION      -- Returns PSCI version (1.1)
//   0x8400_0001  CPU_SUSPEND       -- Suspend calling CPU (32-bit)
//   0xC400_0001  CPU_SUSPEND       -- Suspend calling CPU (64-bit)
//   0x8400_0002  CPU_OFF           -- Power off calling CPU
//   0x8400_0003  CPU_ON            -- Power on a target CPU (32-bit)
//   0xC400_0003  CPU_ON            -- Power on a target CPU (64-bit)
//   0x8400_0004  AFFINITY_INFO     -- Query CPU affinity state (32-bit)
//   0xC400_0004  AFFINITY_INFO     -- Query CPU affinity state (64-bit)
//   0x8400_0006  MIGRATE_INFO_TYPE -- Returns NOT_SUPPORTED (no trusted OS)
//   0x8400_0008  SYSTEM_OFF        -- Power off the entire system
//   0x8400_0009  SYSTEM_RESET      -- Reset the entire system
//   0x8400_000A  PSCI_FEATURES     -- Query supported features

import Foundation

// MARK: - PSCI Function IDs

/// PSCI function identifiers (ARM DEN0022D, Table 2).
///
/// Function IDs use the SMC Calling Convention (SMCCC):
/// - Bit 31: Fast call (1) vs. yielding (0). PSCI uses fast calls.
/// - Bit 30: SMC64 (1) vs. SMC32 (0). 64-bit variants have bit 30 set.
/// - Bits [29:24]: Service range. 0x04 = Standard Secure Service (PSCI).
/// - Bits [15:0]: Function number within the service.
public enum PSCIFunctionID: UInt32 {
    // 32-bit calling convention (SMC32)
    case version          = 0x8400_0000
    case cpuSuspend32     = 0x8400_0001
    case cpuOff           = 0x8400_0002
    case cpuOn32          = 0x8400_0003
    case affinityInfo32   = 0x8400_0004
    case migrateInfoType  = 0x8400_0006
    case systemOff        = 0x8400_0008
    case systemReset      = 0x8400_0009
    case features         = 0x8400_000A
    case systemReset2_32  = 0x8400_0012
    case systemSuspend32  = 0x8400_000E

    // 64-bit calling convention (SMC64)
    case cpuSuspend64     = 0xC400_0001
    case cpuOn64          = 0xC400_0003
    case affinityInfo64   = 0xC400_0004
    case systemReset2_64  = 0xC400_0012
    case systemSuspend64  = 0xC400_000E
}

// MARK: - PSCI Return Codes

/// Standard PSCI return values (ARM DEN0022D, Table 6).
public enum PSCIReturn {
    public static let success: Int32          =  0
    public static let notSupported: Int32     = -1
    public static let invalidParameters: Int32 = -2
    public static let denied: Int32           = -3
    public static let alreadyOn: Int32        = -4
    public static let onPending: Int32        = -5
    public static let internalFailure: Int32  = -6
    public static let notPresent: Int32       = -7
    public static let disabled: Int32         = -8
    public static let invalidAddress: Int32   = -9
}

// MARK: - PSCI Version

/// PSCI version encoding: major in bits [31:16], minor in bits [15:0].
/// This implementation reports PSCI v1.1.
public let psciVersionValue: UInt32 = 0x0001_0001

// MARK: - VM Lifecycle Events

/// Events generated by the PSCI power controller for VM lifecycle management.
///
/// The VMM's vCPU run loop uses these events to coordinate VM-wide state
/// changes like shutdown, reboot, and secondary CPU power-on.
public enum PSCIEvent: Sendable {
    /// The guest requested full system power-off.
    case systemOff

    /// The guest requested a full system reset (reboot).
    case systemReset

    /// The guest requested to power on a secondary CPU.
    /// - Parameters:
    ///   - cpuID: The target CPU's MPIDR affinity value (Aff0 = CPU index).
    ///   - entryPoint: The 64-bit address where the CPU should start executing.
    ///   - contextID: The context ID value to pass in X0 at entry.
    case cpuOn(cpuID: UInt64, entryPoint: UInt64, contextID: UInt64)

    /// The calling CPU requested to power itself off.
    /// - Parameter cpuID: The MPIDR affinity value of the CPU powering off.
    case cpuOff(cpuID: UInt64)

    /// The calling CPU requested to suspend itself.
    /// - Parameters:
    ///   - cpuID: The MPIDR affinity value of the suspending CPU.
    ///   - powerState: The requested PSCI power state.
    ///   - entryPoint: The address to resume execution at.
    case cpuSuspend(cpuID: UInt64, powerState: UInt32, entryPoint: UInt64)
}

// MARK: - CPU Power State

/// Tracks the power state of each virtual CPU for AFFINITY_INFO queries.
public enum CPUPowerState: Sendable {
    /// The CPU is powered on and running.
    case on
    /// The CPU is powered off.
    case off
    /// The CPU is in the process of being powered on (CPU_ON issued but not yet running).
    case onPending
}

// MARK: - Power Controller

/// PSCI power controller for virtual machine power management.
///
/// Decodes PSCI function calls from HVC/SMC exits and translates them into
/// ``PSCIEvent`` callbacks. The VMM's vCPU thread uses this to handle power
/// management requests from the guest OS.
///
/// ## Usage
/// ```swift
/// let psci = PowerController(cpuCount: 4)
/// psci.onEvent = { event in
///     switch event {
///     case .systemOff:
///         try vm.stop()
///     case .cpuOn(let cpuID, let entry, let context):
///         try vm.startSecondaryCPU(cpuID, entry: entry, context: context)
///     // ...
///     }
/// }
/// ```
///
/// ## Threading Model
/// - ``handleCall(functionID:x1:x2:x3:callerCPU:)`` is called from the vCPU
///   thread that trapped the HVC/SMC instruction.
/// - ``onEvent`` is invoked synchronously from the same vCPU thread.
/// - CPU state queries (``cpuState(for:)``) are thread-safe.
public final class PowerController: @unchecked Sendable {

    // MARK: - Properties

    /// The number of virtual CPUs in the system.
    public let cpuCount: Int

    /// Called when a PSCI event occurs. The VMM should handle lifecycle changes
    /// in response to these events.
    public var onEvent: ((PSCIEvent) -> Void)?

    // MARK: - Internal State

    private let lock = NSLock()
    private var cpuStates: [CPUPowerState]

    // MARK: - Initialization

    /// Create a PSCI power controller.
    ///
    /// CPU 0 starts in the `.on` state (boot CPU). All other CPUs start `.off`.
    ///
    /// - Parameter cpuCount: Total number of virtual CPUs.
    public init(cpuCount: Int) {
        self.cpuCount = cpuCount
        self.cpuStates = Array(repeating: .off, count: cpuCount)
        if cpuCount > 0 {
            cpuStates[0] = .on
        }
    }

    // MARK: - CPU State

    /// Query the current power state of a CPU.
    ///
    /// - Parameter cpuIndex: The CPU index (0-based).
    /// - Returns: The power state, or `nil` if the index is out of range.
    public func cpuState(for cpuIndex: Int) -> CPUPowerState? {
        lock.lock()
        defer { lock.unlock() }
        guard cpuIndex >= 0, cpuIndex < cpuStates.count else { return nil }
        return cpuStates[cpuIndex]
    }

    /// Mark a CPU as powered on (call when the CPU has actually started running).
    ///
    /// - Parameter cpuIndex: The CPU index to mark as on.
    public func markCPUOn(_ cpuIndex: Int) {
        lock.lock()
        defer { lock.unlock() }
        guard cpuIndex >= 0, cpuIndex < cpuStates.count else { return }
        cpuStates[cpuIndex] = .on
    }

    /// Mark a CPU as powered off.
    ///
    /// - Parameter cpuIndex: The CPU index to mark as off.
    public func markCPUOff(_ cpuIndex: Int) {
        lock.lock()
        defer { lock.unlock() }
        guard cpuIndex >= 0, cpuIndex < cpuStates.count else { return }
        cpuStates[cpuIndex] = .off
    }

    /// Reset all CPUs to their initial power state (CPU 0 on, rest off).
    public func reset() {
        lock.lock()
        for i in 0..<cpuStates.count {
            cpuStates[i] = (i == 0) ? .on : .off
        }
        lock.unlock()
    }

    // MARK: - PSCI Call Handling

    /// Handle a PSCI function call from an HVC or SMC trap.
    ///
    /// This method decodes the PSCI function ID and arguments, performs the
    /// requested operation, and returns the PSCI return value that should be
    /// placed in the calling vCPU's X0 register.
    ///
    /// - Parameters:
    ///   - functionID: The PSCI function ID from X0 (the raw UInt32 value).
    ///   - x1: The value of register X1 (first argument).
    ///   - x2: The value of register X2 (second argument).
    ///   - x3: The value of register X3 (third argument).
    ///   - callerCPU: The index of the calling vCPU.
    /// - Returns: A ``PSCICallResult`` indicating the return value and whether
    ///   the calling vCPU should continue running.
    public func handleCall(
        functionID: UInt32,
        x1: UInt64,
        x2: UInt64,
        x3: UInt64,
        callerCPU: Int
    ) -> PSCICallResult {
        guard let function = PSCIFunctionID(rawValue: functionID) else {
            // Unknown PSCI function -- return NOT_SUPPORTED.
            return PSCICallResult(returnValue: PSCIReturn.notSupported, continueExecution: true)
        }

        switch function {
        case .version:
            return handleVersion()

        case .cpuOn32, .cpuOn64:
            return handleCPUOn(targetCPU: x1, entryPoint: x2, contextID: x3)

        case .cpuOff:
            return handleCPUOff(callerCPU: callerCPU)

        case .cpuSuspend32, .cpuSuspend64:
            return handleCPUSuspend(
                callerCPU: callerCPU,
                powerState: UInt32(truncatingIfNeeded: x1),
                entryPoint: x2
            )

        case .affinityInfo32, .affinityInfo64:
            return handleAffinityInfo(targetAffinity: x1, lowestLevel: UInt32(truncatingIfNeeded: x2))

        case .systemOff:
            return handleSystemOff()

        case .systemReset, .systemReset2_32, .systemReset2_64:
            return handleSystemReset()

        case .features:
            return handleFeatures(queryID: UInt32(truncatingIfNeeded: x1))

        case .migrateInfoType:
            // Trusted OS migration not supported.
            return PSCICallResult(returnValue: PSCIReturn.notSupported, continueExecution: true)

        case .systemSuspend32, .systemSuspend64:
            // System suspend is treated like CPU suspend for the boot CPU.
            return handleCPUSuspend(
                callerCPU: callerCPU,
                powerState: UInt32(truncatingIfNeeded: x1),
                entryPoint: x2
            )
        }
    }

    // MARK: - Individual PSCI Handlers

    private func handleVersion() -> PSCICallResult {
        // Return PSCI v1.1 as a positive integer (not a PSCI error code).
        let versionAsUInt64 = UInt64(psciVersionValue)
        return PSCICallResult(
            returnValue: Int32(bitPattern: UInt32(truncatingIfNeeded: versionAsUInt64)),
            continueExecution: true
        )
    }

    private func handleCPUOn(targetCPU: UInt64, entryPoint: UInt64, contextID: UInt64) -> PSCICallResult {
        let cpuIndex = Int(targetCPU & 0xFF) // Aff0 = CPU index

        guard cpuIndex >= 0, cpuIndex < cpuCount else {
            return PSCICallResult(returnValue: PSCIReturn.invalidParameters, continueExecution: true)
        }

        lock.lock()
        let currentState = cpuStates[cpuIndex]

        switch currentState {
        case .on:
            lock.unlock()
            return PSCICallResult(returnValue: PSCIReturn.alreadyOn, continueExecution: true)

        case .onPending:
            lock.unlock()
            return PSCICallResult(returnValue: PSCIReturn.onPending, continueExecution: true)

        case .off:
            cpuStates[cpuIndex] = .onPending
            lock.unlock()
            onEvent?(.cpuOn(cpuID: targetCPU, entryPoint: entryPoint, contextID: contextID))
            return PSCICallResult(returnValue: PSCIReturn.success, continueExecution: true)
        }
    }

    private func handleCPUOff(callerCPU: Int) -> PSCICallResult {
        lock.lock()
        if callerCPU >= 0, callerCPU < cpuStates.count {
            cpuStates[callerCPU] = .off
        }
        lock.unlock()

        onEvent?(.cpuOff(cpuID: UInt64(callerCPU)))

        // CPU_OFF does not return -- the vCPU should stop its run loop.
        return PSCICallResult(returnValue: PSCIReturn.success, continueExecution: false)
    }

    private func handleCPUSuspend(
        callerCPU: Int,
        powerState: UInt32,
        entryPoint: UInt64
    ) -> PSCICallResult {
        onEvent?(.cpuSuspend(
            cpuID: UInt64(callerCPU),
            powerState: powerState,
            entryPoint: entryPoint
        ))

        // For power-down suspend, the CPU would stop; for standby, it continues.
        // Bit 16 of power_state: 0 = standby, 1 = power-down.
        let isPowerDown = (powerState & (1 << 16)) != 0
        return PSCICallResult(returnValue: PSCIReturn.success, continueExecution: !isPowerDown)
    }

    private func handleAffinityInfo(targetAffinity: UInt64, lowestLevel: UInt32) -> PSCICallResult {
        let cpuIndex = Int(targetAffinity & 0xFF)

        guard cpuIndex >= 0, cpuIndex < cpuCount else {
            return PSCICallResult(returnValue: PSCIReturn.invalidParameters, continueExecution: true)
        }

        lock.lock()
        let state = cpuStates[cpuIndex]
        lock.unlock()

        // AFFINITY_INFO returns:
        //   0 = ON
        //   1 = OFF
        //   2 = ON_PENDING
        let affinityValue: Int32
        switch state {
        case .on:
            affinityValue = 0
        case .off:
            affinityValue = 1
        case .onPending:
            affinityValue = 2
        }

        return PSCICallResult(returnValue: affinityValue, continueExecution: true)
    }

    private func handleSystemOff() -> PSCICallResult {
        onEvent?(.systemOff)
        // SYSTEM_OFF does not return.
        return PSCICallResult(returnValue: PSCIReturn.success, continueExecution: false)
    }

    private func handleSystemReset() -> PSCICallResult {
        onEvent?(.systemReset)
        // SYSTEM_RESET does not return.
        return PSCICallResult(returnValue: PSCIReturn.success, continueExecution: false)
    }

    private func handleFeatures(queryID: UInt32) -> PSCICallResult {
        // Check if the queried PSCI function is supported.
        let supported: Bool
        switch queryID {
        case PSCIFunctionID.version.rawValue,
             PSCIFunctionID.cpuOn32.rawValue,
             PSCIFunctionID.cpuOn64.rawValue,
             PSCIFunctionID.cpuOff.rawValue,
             PSCIFunctionID.cpuSuspend32.rawValue,
             PSCIFunctionID.cpuSuspend64.rawValue,
             PSCIFunctionID.affinityInfo32.rawValue,
             PSCIFunctionID.affinityInfo64.rawValue,
             PSCIFunctionID.systemOff.rawValue,
             PSCIFunctionID.systemReset.rawValue,
             PSCIFunctionID.features.rawValue:
            supported = true
        default:
            supported = false
        }

        return PSCICallResult(
            returnValue: supported ? PSCIReturn.success : PSCIReturn.notSupported,
            continueExecution: true
        )
    }
}

// MARK: - Call Result

/// The result of handling a PSCI call.
///
/// Contains the return value to place in X0 and whether the calling vCPU
/// should continue executing or halt (e.g., for CPU_OFF, SYSTEM_OFF).
public struct PSCICallResult: Sendable {
    /// The PSCI return value to place in the calling vCPU's X0 register.
    /// Cast to UInt64 for register write: `UInt64(bitPattern: Int64(returnValue))`.
    public let returnValue: Int32

    /// Whether the calling vCPU should continue its run loop after this call.
    /// `false` for CPU_OFF, SYSTEM_OFF, SYSTEM_RESET, and power-down CPU_SUSPEND.
    public let continueExecution: Bool

    public init(returnValue: Int32, continueExecution: Bool) {
        self.returnValue = returnValue
        self.continueExecution = continueExecution
    }

    /// The return value as a UInt64 suitable for writing to the X0 register.
    /// Negative PSCI return codes are sign-extended to 64 bits.
    public var x0Value: UInt64 {
        UInt64(bitPattern: Int64(returnValue))
    }
}
